INFO:root:XWEAT started
INFO:root:Translating terms from en to es
INFO:root:Embeddings are in vec format
INFO:gensim.models.utils_any2vec:loading projection weights from /disk/scratch/v1rmuoz2/weat_temp/data/
Traceback (most recent call last):
  File "xweat/weat.py", line 693, in <module>
    args = main()
  File "xweat/weat.py", line 590, in main
    train_weat(args)
  File "xweat/weat.py", line 669, in train_weat
    embd_dict = load_embedding_dict(embeddings_path=args.embeddings, glove=False)
  File "xweat/weat.py", line 498, in load_embedding_dict
    embd_dict = utils.load_embeddings(embeddings_path, word2vec=True)
  File "/home/v1rmuoz2/embedding_bias/scripts/xweat/utils.py", line 107, in load_embeddings
    model = gensim.models.KeyedVectors.load_word2vec_format(path)
  File "/home/v1rmuoz2/conda/envs/gensim/lib/python3.7/site-packages/gensim/models/keyedvectors.py", line 1498, in load_word2vec_format
    limit=limit, datatype=datatype)
  File "/home/v1rmuoz2/conda/envs/gensim/lib/python3.7/site-packages/gensim/models/utils_any2vec.py", line 342, in _load_word2vec_format
    with utils.open(fname, 'rb') as fin:
  File "/home/v1rmuoz2/conda/envs/gensim/lib/python3.7/site-packages/smart_open/smart_open_lib.py", line 187, in open
    newline=newline,
  File "/home/v1rmuoz2/conda/envs/gensim/lib/python3.7/site-packages/smart_open/smart_open_lib.py", line 287, in _shortcut_open
    return _builtin_open(local_path, mode, buffering=buffering, **open_kwargs)
IsADirectoryError: [Errno 21] Is a directory: '/disk/scratch/v1rmuoz2/weat_temp/data/'
